### ISSUE TITLE
Fenced frame appears broken in latest Chromium revision

### ISSUE THREAD

**Issue by MarcoLugo** [GoogleChromeLabs/fledge-demo-remote#4]
Sorry, I don't think this is related to the `fledge-demo` itself but I did not know where to go with this, maybe someone here can forward the issue to the right place.

It seems like the latest development chromium versions broke the fenced frame and thus the demo. I also noticed this in my own tests outside https://fledge-demo.glitch.me. The ad does show with chromium revision [991192](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/991192/) (102.0.4999.0) but it is no longer the case with revision [994825](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/994825/) (103.0.5018.0). I did not set out to find the exact revision where it no longer works but hopefully this is informative enough to help. As you can see from the images below, the fenced frame in the latter version looks as if width and height were compressed.

Revision 991192:
![revision_991192](https://user-images.githubusercontent.com/6843447/164544475-9b2569e6-1920-4a61-8be6-5b28a1ec3291.png)

Revision 994825:
![revision_994825](https://user-images.githubusercontent.com/6843447/164544497-f343ecf2-0833-4f99-a912-aeb4214ccbf1.png)

**Comment by samdutton** [comment]
@MarcoLugo Just to say — haven't forgotten this! Just checking what's going on.

**Comment by kevinkiklee** [comment]
Hi @MarcoLugo.  Sorry it took some time to get back to you. The reason why the ad isn't rendering in a fenced frame is because: 
* The `PrivacySandboxAdsAPIsOverride` flag needs to be included in the Chrome starting arguments. (`--enable-features=InterestGroupStorage,AdInterestGroupAPI,Fledge,FencedFrames,PrivacySandboxAdsAPIsOverride`)
* The fenced frame tag's `mode` attribute needs to be set to `opaque-ads`. (Example: `<fencedframe id='fledge-ad' mode='opaque-ads'></fencedframe>`)

---

We are in the process of migrating the FLEDGE demo to a different hosting solution at the moment, and the existing demo at https://fledge-demo.glitch.me has not been updated yet. While we make the full switch, you can check out the fenced frame functionality at https://fledge-demo.web.app/ (Repo: https://github.com/GoogleChromeLabs/fledge-demo/).
